import { lazy } from 'react'

export const Home = lazy(() => import('../pages/Home'))
export const About = lazy(() => import('../pages/About'))
export const NotFound = lazy(() => import('../pages/NotFound'))
export const PerfilGeneral = lazy(() => import('../pages/Dashboard/perfil/PerfilGeneral'))
export const PerfilEditar = lazy(() => import('../pages/Dashboard/perfil/PerfilEditar'))
export const PerfilTelefonos = lazy(() => import('../pages/Dashboard/perfil/PerfilTelefonos'))
export const PerfilPortafolio = lazy(() => import('../pages/Dashboard/perfil/PerfilPortafolio'))
export const Proyectos = lazy(() => import('../features/proyectos/pages/PageProyectos'))
export const Habilidades = lazy(() => import('../features/habilidades/pages/PageHabilidades'))
export const Login = lazy(() => import('../pages/auth/Login'))
export const Register = lazy(() => import('../pages/auth/Register'))
export const Certificaiones = lazy(() => import('../features/certificaciones/page/Certificaciones')) 
export const Hitos = lazy(() => import('../features/hitos/page/Hitos')) 
export const MensajesPrincipal = lazy(() => import('../pages/Dashboard/mensajes/MensajesPrincipal'))
export const MensajesRecibidos = lazy(() => import('../pages/Dashboard/mensajes/MensajesRecibidos'))
export const MensajesEnviados = lazy(() => import('../pages/Dashboard/mensajes/MensajesEnviados'))
export const MensajesDestacados = lazy(() => import('../pages/Dashboard/mensajes/MensajesDestacados'))
export const Configuracion = lazy(() => import('../features/configuracion/page/Configuracion')) 
export const Estadisticas = lazy(() => import('../features/reportesUsuario/page/ReportesUsr'))
export const VistaProyecto = lazy(() => import('../features/vistaProyectos/pages/PageVistaProyecto'))
export const VisibilidadComponentes = lazy(() => import('../pages/Dashboard/configuraciones/VisibilidadComponentes')) 
export const VisibilidadGeneral = lazy(() => import('../pages/Dashboard/configuraciones/VisibilidadGeneral'))
export const CambiarPlantilla = lazy(() => import('../pages/Dashboard/configuraciones/CambiarPlantilla'))
